# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_new_file_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# -----------------------------------------------------------------------------
# cnf_window / create_new_file_window (cnf)
# -----------------------------------------------------------------------------
# After clicking on the <create> button, this window appears
#
# The window has one field for entering the file name and
# a button that creates the file
# -----------------------------------------------------------------------------


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CnfWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(584, 61)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.field_entering_name_new_file = QtWidgets.QLineEdit(self.centralwidget)
        self.field_entering_name_new_file.setGeometry(QtCore.QRect(10, 10, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.field_entering_name_new_file.setFont(font)
        self.field_entering_name_new_file.setObjectName("field_entering_name_new_file")

        self.button_create_new_file = QtWidgets.QPushButton(self.centralwidget)
        self.button_create_new_file.setGeometry(QtCore.QRect(490, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_create_new_file.setFont(font)
        self.button_create_new_file.setObjectName("create_new_file_button")

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Create a new file"))
        self.button_create_new_file.setText(_translate("MainWindow", "Create"))
